### ISSUE TITLE
Optimize for Mobile

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/webmaker-curriculum#100]
The new template doesn't look snazzy on mobile, buttons move around etc. This issue is to make our curriculum repo mobile optimized :)

**Comment by dajbelshaw** [comment]
Who do we need to help with this - @iamjessklein?

**Comment by iamjessklein** [comment]
is this tied to a heartbeat? I'm happy to work on it when it's tied to a heartbeat. 
cc/ @davidascher

**Comment by dajbelshaw** [comment]
Hi @iamjessklein - it's tied to March 27th at the moment. Would you prefer it to be in the main /plan repo?

**Comment by iamjessklein** [comment]
I believe that's how it gets to TPS, I could be wrong though. cc @thisandagain  is that right?

**Comment by thisandagain** [comment]
Yup! Needs to be attached to the scope of work of an existing `/plan` ticket or have a new one created. @hannahkane is your PM to help prioritize this.

**Comment by hannahkane** [comment]
I createe a ticket in the /plan repo for March 27, though we'll look at in the context of the other priorities when we actually do the planning for that heartbeat.

https://github.com/MozillaFoundation/plan/issues/301

**Comment by dajbelshaw** [comment]
Thanks @hannahkane!

**Comment by LauraHilliger** [comment]
Previously moved to mozilla-learning
