### ISSUE TITLE
Curriculum build: Appmaker for Canadian educators

### ISSUE THREAD

**Issue by keyboardkat** [mozilla/webmaker-curriculum#105]
Goal: Build a teaching kit that aggregates Appmaker activities useful for Canadian educators for a CIRA granted project. Format will be in Github pages, but Thimble friendly.

Sections to include, from @smithisgeneric: 
* Learning objectives
* Interlinked activities to teach web literacy skills 
* Template for remix to meet Canadian educators needs (i.e. "remix" button and contextualization of some examples of curriculum/programming links in Canada)
* Links to user priorities (user research outputs) from hackathon in Toronto. Summary report [here](https://docs.google.com/document/d/1Wr0CYSeq5sDYeVthUoZ8I-zk7pnbGpNVGu-M7f5H2ss/edit#heading=h.74kqsg72q0rt).

Deadline for first draft of curriculum: *Jan 28*

**Comment by keyboardkat** [comment]
Activities to include: 

* [Mobile design kit](https://jess.makes.org/thimble/MTMyMzM2ODQ0OA==/mobile-design-kit)
* Appmaker music tutorial ( @smithisgeneric do you have a link for this? can't find on site)
* Becky's cat tutorial (@smithisgeneric, do you have a link for this?)
* Choose your own adventure logic pathway by @LauraHilliger 

Any others?

**Comment by secretrobotron** [comment]
While activity was hot, I was compiling stuff in this gallery: https://webmaker.org/gallery/list/53fe24bc21d4817b6c000aad

Might be helpful for now. I'll have a look around though!

**Comment by smithisgeneric** [comment]
Start of the links track down for @keyboardkat 

Music tutorial https://secretrobotron.makes.org/thimble/OTA1NzA3NTIw/make-music-with-appmaker
Trivia app https://second-fly-746.webmak.es/install

**Comment by iamjessklein** [comment]
+ @laurad who might have some input as to how we can tweak some of the templates based on her user testing work.

**Comment by keyboardkat** [comment]
Thanks so much for the links, @secretrobotron @smithisgeneric! Making a list and drafting the first draft now!

**Comment by keyboardkat** [comment]
@smithisgeneric requesting initial feedback on teaching kit draft: https://etherpad.mozilla.org/appmakeredkit (think i got most of the sections here, but please let me know what i've missed!)

**Comment by keyboardkat** [comment]
Update: Teaching kit now live at https://keyboardkat.makes.org/thimble/MTEzODQyNjExMg==/appmaker-for-educators-teaching-kit

Finishing today and tomorrow. If useful, can also port raw code to Github in case future users want to remix elsewhere, outside of Thimble.

**Comment by dajbelshaw** [comment]
Great! Thanks Kat, looking good. Was going to ask on the status of this but glad you'll have it finished this week. :)

PS Love the main image. Where's that from?

**Comment by keyboardkat** [comment]
Thanks Dr @dajbelshaw! :) TBH, I have no idea where img from at this point - have had it on my various computers forever! 

@smithisgeneric have now updated side bar images for both printable resources and CIRA acknowledgement. let me know if these work? other than that, kit should be ready for you to transfer to Hive Toronto account: https://keyboardkat.makes.org/thimble/MTEzODQyNjExMg==/appmaker-for-educators-teaching-kit

**Comment by dajbelshaw** [comment]
Paging @smithisgeneric to see if this make is now on the Hive Toronto account? 

https://keyboardkat.makes.org/thimble/MTEzODQyNjExMg==/appmaker-for-educators-teaching-kit
