### ISSUE TITLE
Create learning objectives for 2. Writing the Web: Composing for the Web

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/webmaker-curriculum#111]
Session 2 of Web Literacy Basics I should focus on the competency Composing for the Web. The original meta arc included a set of activities for this competency as well. #112 is the activity creation issue.

-----
**Update:** after discussion with community, we now have learning objectives:

* Summarize the most commonly-used HTML tags
* Use HTML tags to re-structure a web page
* Create a web page for a specific audience

**Comment by dajbelshaw** [comment]
#onit https://webmaker.org/en-US/resources/literacy/weblit-Composing

**Comment by dajbelshaw** [comment]
OK, first go at three learning objectives using [this wiki page](https://github.com/mozilla/webmaker-curriculum/wiki/How-to-write-Learning-Objectives) and the [Composing for the Web](https://webmaker.org/en-US/resources/literacy/weblit-Composing) skills as guidance *(a.k.a. dogfooding!)*

* Summarize the 10 most commonly-used HTML tags*
* Use HTML tags to re-structure a basic web page
* Create a web page from scratch for a specific audience

\* See [this](http://www.99lime.com/_bak/topics/you-only-need-10-tags/), for example

**Comment by dajbelshaw** [comment]
Still waiting for review from @smithisgeneric and @LauraHilliger. Happy for others to weigh in before closing this. :)

**Comment by dajbelshaw** [comment]
Closing this.

**Comment by dajbelshaw** [comment]
Shouldn't have closed this - reopening for community review.

**Comment by dajbelshaw** [comment]
During conversation with @ldecoursy and @thornet yesterday, we decided to:

* Remove learning objectives not directly related to 'Composing for the Web' competency
* Create a Discourse thread for feedback on these learning objectives

Will re-scope. :)

**Comment by dajbelshaw** [comment]
Further to conversation with @thornet and @ldecoursy yesterday, have opened thread on Discourse for community feedback:

http://discourse.webmaker.org/t/learning-objectives-composing-for-the-web/1171

**Comment by dajbelshaw** [comment]
OK, so after some great input from the community, we've got:
- Summarize the most commonly-used HTML tags
- Use HTML tags to re-structure a web page
- Create a web page for a specific audience 

/ cc @thornet @omnignorant @smithisgeneric @ldecoursy
