### ISSUE TITLE
Create activity for 2. Writing for the Web: Composing for the Web

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/webmaker-curriculum#112]
#111 is covering the learning objectives, and this ticket is for the activity. See also #113  In the original meta arc I made these suggestions for Composing (but perhaps the community wants to discuss / share what they've got?)

**Writing for the Web: Composing HTML** (45 mins) This unit demystifies HTML.
 * (5 mins) Introduction round
 * (10 mins) Your first Webpage: Facilitator explains the 5 basic tags and text formatting. Participants then practice writing their first webpages. [Quick write of the activity from @chadsansing](https://docs.google.com/document/d/1Ak82b-pCFuQ_DjLCoXUsRlb5jIZ1Snu703BOaYw2JdI/edit?token=AC4w5VixddWNc_PrY2NClLmTaAO2EJ8i1g:1404326211074&skipDomain=true)
Facilitator explains links, images and embeds. Participants then extend their first webpages: [@chadsansing rules. Another write up](https://docs.google.com/document/d/1X8bu2vNHax00STKdHlBASEfJmp707tlR_G_5J5GIaR8/edit?token=AC4w5VhSZ19VPwh7_jGQNYn8oJXVudAKEg:1404325493254&skipDomain=false)
 * (30 mins) Remixing a page: Once learners have successfully written a bit of HTML/CSS, the Facilitator asks them to remix the [Internet Defense League starter make](https://mozteach.makes.org/thimble/hack-the-web-with-thimble)

**Comment by dajbelshaw** [comment]
Suggest we might want to separate these lessons out, but for now just flagging that we might want to dive into HTML using something like this: http://www.99lime.com/_bak/topics/you-only-need-10-tags/

**Comment by dajbelshaw** [comment]
Closing this in favour of Issue #135 (easier to grok for community)
