### ISSUE TITLE
Prepare codesign asks

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/webmaker-curriculum#117]
Paging @keyboardkat and @dajbelshaw 

After talking with Doug, we thought it would be a good idea to specifically invite the community in the clubs call next week to help us design the curriculum. I added an item to the agenda here: https://teach.etherpad.mozilla.org/club-calls

Maybe we should also think about writing a blog post about codesign and including it with the monthly @hannahkane publishes?

**Comment by dajbelshaw** [comment]
Absolutely - we could publish the post on the Webmaker blog. :)

**Comment by keyboardkat** [comment]
cheers @LauraHilliger @dajbelshaw - this is definitely what i'd like to happen. i've added specific names into the etherpad, with a call-out for others to get involved who aren't listed yet. 

@dajbelshaw shall we take a crack at it? maybe tomorrow? i'll be around...

**Comment by dajbelshaw** [comment]
Definitely. As I put in an email earlier, I'd love to talk through your experience of co-design with 10+ people. There's the additional challenge of everyone being geographically dispersed, but I'm definitely looking forward to the challenge! :)

**Comment by dajbelshaw** [comment]
Done - added to https://teach.etherpad.mozilla.org/club-calls
