### ISSUE TITLE
Write learning objectives for 3. Participating on the Web: Open Practices

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/webmaker-curriculum#118]
The final session for Web Literacy Basics I should be Open Practices, and boy do we know about that :wink: On [Training](http://training.webmakerprototypes.org), we have a lot of diverse content that we can pull from if were looking for language, but also collaborative activities like [scrumming](https://laura.makes.org/thimble/mini-makers-scrum), [mindmapping](https://laura.makes.org/thimble/collaborative-mindmapping) or [speedgeeking](https://laura.makes.org/thimble/LTE3MzEzOTU1ODQ=/speed-geek-connecting) are good ways to prepare people for the working openly pieces inherent in the entire Connecting Strand.

Other places to look at, particularly for the skills under [Open Practices](https://webmaker.org/en-US/resources/literacy/weblit-OpenPractices), include [P2PU](http://p2pu.org) and [School of Open](http://schoolofopen.org)

**Comment by dajbelshaw** [comment]
I guess the issue here might be that we know *too* much and therefore lack empathy with those new to this area. I'm a big fan of the things you mention, but we could start with just **why work open?**

http://openmatt.org/2011/04/06/how-to-work-open/

**Comment by dajbelshaw** [comment]
Starting work on this soon. For now, will just point to the [Open Practices](https://webmaker.org/en-US/resources/literacy/weblit-OpenPractices) competency on webmaker.org, and list the **skills** (these aren't _learning objectives_ yet):
- Distinguishing between open and closed licensing
- Making web resources available under an open license
- Using and sharing files in open, web-friendly formats when appropriate
- Contributing to an Open Source project

**Comment by dajbelshaw** [comment]
OK, think a lot of this will probably depend on the activities we choose, but here's some **learning objectives** as a starter for ten:
- Identify openly-licensed resources
- Locate and use resources under an open license
- Create a resource and share it in an open, web-friendly format

/ @ldecoursy is the plan to put these into Discourse again and ask the community to help? :)

**Comment by ldecoursy** [comment]
That sounds great. Let me know if you have time to set that up before the call tomorrow or I can do.

**Comment by dajbelshaw** [comment]
OK @ldecoursy have created thread here, ready for the call: http://discourse.webmaker.org/t/learning-objectives-open-practices/1194

**Comment by dajbelshaw** [comment]
As of right now we have:
- Locate and collect openly-licensed resources
- Create a resource at a publicly-accessible URL
- Share a resource in an open, web-friendly format

Unless there's any further action on the Discourse thread, let's go with these! :+1:

**Comment by dajbelshaw** [comment]
Update after further activity in the Discourse thread:
- Use a search engine to locate and collect openly-licensed resources
- Create a resource at a publicly-accessible URL
- Collaborate with others by sharing a resource in an open, web-friendly format

I'm happy with these learning objectives, but won't be around for creating activities around them for 3rd Club test on 20th February. I'll be on holiday!

/ cc @thornet
