### ISSUE TITLE
Create landing page for curriculum testing

### ISSUE THREAD

**Issue by thornet** [mozilla/webmaker-curriculum#120]
@LauraHilliger: could we ship a landing page that explains how to test the first section of Web LIt Basics I? 

We should make it a super simple, sequenced list. 

Proposal: 

1. Brief intro. 
2. Pre questionnaire. 
3. List of activities linking off to full pages. 
4. Post questionnaire. 
5. Reflection.  

Can help with copy.

**Comment by dajbelshaw** [comment]
Created wiki page: https://github.com/mozilla/webmaker-curriculum/wiki/How-to-test-Web-Literacy-Basics-I

**Comment by thornet** [comment]
Thanks! Added the key info.

@ldecoursy: mind reviewing? We should set the dates for the calls as well.

**Comment by LauraHilliger** [comment]
Do you want to stick with the wiki as the landing? Might actually be better because people can poke around in the github and see what's what. They'll also see the index of other wiki pages. 

Otherwise, we can use the github.io landing page to be whatever we need it to be: http://mozilla.github.io/webmaker-curriculum/

**Comment by dajbelshaw** [comment]
After next week's call we should link to the co-design process for Web Literacy Basics II.

**Comment by thornet** [comment]
Migrating wiki content to: http://mozilla.github.io/webmaker-curriculum/WebLiteracyBasics-I/index.html

**Comment by dajbelshaw** [comment]
Awesome. Happy to edit directly but ended up in merge conflicts hell with @LauraHilliger last time, so...

https://redpen.io/ez53a18df33c6c97b6

**Comment by thornet** [comment]
Big overhaul: http://mozilla.github.io/webmaker-curriculum/WebLiteracyBasics-I/

@dajbelshaw @ldecoursy: have a peek?

**Comment by thornet** [comment]
Notes: 
* need to add dates for calls
* need to update links for questionnaires and activities
* proofread

Also, feedback on layout is helpful!

**Comment by thornet** [comment]
Notes:

- [ ] need to add dates for calls
- [ ] need to update links for questionnaires and activities
- [ ] proofread

Also, feedback on layout is helpful!

**Comment by dajbelshaw** [comment]
Definitely like the way this is heading @thornet! :)

Some comments: https://redpen.io/uw33f7dfe0514b7e97

**Comment by ldecoursy** [comment]
Link to pre survey: http://goo.gl/forms/Uua6yKIy5E
Link to post survey: http://goo.gl/forms/ezm6IXWhhM

Where is the best place to feedback on the reflection prompts? I think we should add Karen's q:
What was the biggest "aha" moment for your learners during the activity?

**Comment by dajbelshaw** [comment]
Hey @ldecoursy could we discuss this in Issue #88 perhaps?

**Comment by thornet** [comment]
Thanks for the links and edit suggestions! Have filed and live now at: 

http://mozilla.github.io/webmaker-curriculum/WebLiteracyBasics-I/

Marking as closed.
