### ISSUE TITLE
Create guidance for mentors advertising their Club

### ISSUE THREAD

**Issue by dajbelshaw** [mozilla/webmaker-curriculum#122]
Just been on a call with [Chris Wilde](https://twitter.com/chriswilde78). He and I are going to be running a Club starting February 10th at [North Tyneside CLC](http://www.ntclc.org.uk/). :smiley_cat: 

We're going to be putting together the event page over the next few days but I realised we don't have a good description of what Clubs *are*. To some extent the event description is the responsibility of mentors - but we could help them out, I think.

The guidance could also point them towards using https://events.webmaker.org rather than Eventbrite, etc. It could include tagging information and pull a lot from the excellent [Maker Party help section](https://party.webmaker.org/en-US/resources).

**Comment by dajbelshaw** [comment]
Let's iterate on this: https://github.com/mozilla/webmaker-curriculum/wiki/How-to-advertise-your-Webmaker-Club

**Comment by LauraHilliger** [comment]
I also started mashing up @chadsansing's work from a while back. Have been hacking here:
http://mozilla.github.io/webmaker-curriculum/StartHere/starting-club.html

and there is another markdown file for running a club started in the StartHere folder: https://github.com/mozilla/webmaker-curriculum/tree/master/StartHere

**Comment by dajbelshaw** [comment]
Oh sorry, I'll close this and remove that page. Should have looked more closely! Thanks, Laura :)
