### ISSUE TITLE
Write learning objectives for Reading the Web: Web Mechanics (Ping Kong activity)

### ISSUE THREAD

**Issue by dajbelshaw** [mozilla/webmaker-curriculum#124]
We need to decide to what extent we're weaving in the **Infrastructure** competency here as well as it affects the learning objectives. At the moment we list **Search** but this activity doesn't cover this competency as far as I can tell! 

PS I found [this diagram](https://raw.githubusercontent.com/wiki/basho/webmachine/images/http-headers-status-v3.png?imm_mid=0cb352&cmp=em-web-na-na-newsltr_20150121) which may help via the [O'Reilly Web Newsletter](http://post.oreilly.com/form/oreilly/viewhtml/9z1zbcand9f68kelidikm3hb4la0c0noijdeirtp0s0?imm_mid=0cb352&cmp=em-web-na-na-newsltr_20150121).

/ cc @thornet @LauraHilliger

**Comment by thornet** [comment]
Agree that Search isn't part of the Ping Kong activity. Seems like definitely Web Mechanics and some of Navigation though: 

* Using and understanding the differences between URLs, IP addresses and search terms (WM)
* Reading, evaluating, and manipulating URLs (N)
* Using hyperlinks to access a range of resources on the web (N)

That O'Reilly diagram looks too complicated for this lesson.

**Comment by dajbelshaw** [comment]
Oh absolutely, wasn't flagging for inclusion in the lesson as-is. Just popped into my inbox and seemed relevant given our discussion of a visual overview. Would need to be *way* simpler. :)

I like the offline twist on **Navigation**. Let's go with that. :+1: 

----

PS Thinking about this made me think we should [combine 'Web Mechanics' and 'Infrastructure'](https://github.com/mozilla/webliteracymap/issues/10) in v1.5 of the Web Literacy Map

**Comment by dajbelshaw** [comment]
OK, here's a starter for ten, using a skill from each **Navigation**, **Web Mechanics** and **Infrastructure**. Per the above comment, the last of these will probably end up in Web Mechanics anyway!

* Read, evaluate and manipulate URLs
* Demonstrate the differences between URLs, IP addresses and search terms
* Describe the practical differences between the web and the Internet

Please review @smithisgeneric & @LauraHilliger :)

**Comment by ldecoursy** [comment]
Also @smithisgeneric would be great if you could draft 3 pre/post survey q's for this as you did for Kraken the Code!

**Comment by dajbelshaw** [comment]
Just to be clear, @smithisgeneric & @ldecoursy  that's Issue #79 (I've renamed some issues to make it clearer!)

**Comment by thornet** [comment]
Thanks, @dajbelshaw! Added these objectives to the Ping Kong page.

**Comment by dajbelshaw** [comment]
Great, closing this then. :)
