### ISSUE TITLE
Proofread Ping Kong activity 

### ISSUE THREAD

**Issue by thornet** [mozilla/webmaker-curriculum#126]
http://mozilla.github.io/webmaker-curriculum/WebLiteracyBasics-I/session01-pingkong.html

@omnignorant @dajbelshaw @ldecoursy would you mind proofreading?

- [x] add learning objectives
- [x] image attribution
- [x] proofread
- [x] check links

**Comment by ldecoursy** [comment]
I think this is lookin good. Do we know if there's an existing glossary for the terms at the top? Would be good to link to a useful resource if one exists, or perhaps someone can help put that together.

Once we have draft learning objectives (@dajbelshaw is that something you can help with?) we can see if @smithisgeneric can do similar pre/post questions for this activity.

**Comment by dajbelshaw** [comment]
I've started putting together a glossary (Issue #89) but needs some attention. Please do dump terms at the bottom of this wiki page for disambiguation/definition: https://github.com/mozilla/webmaker-curriculum/wiki/Glossary :)

**Comment by thornet** [comment]
@dajbelshaw yes, would be great if you could make the glossary! The activity has some definitions already, but maybe a quick MDN/Google search to complete the rest?

**Comment by thornet** [comment]
Feel free to let me know if you find any typos or have suggestions of what to fix. Currently missing questionnaire, but the rest is ready so marking closed.

**Comment by dajbelshaw** [comment]
Just wanted to say that this is looking fantastic with the images included. Skills!
