### ISSUE TITLE
Prepare Discourse thread with reflection prompts

### ISSUE THREAD

**Issue by thornet** [mozilla/webmaker-curriculum#130]
Placeholder here: 

http://discourse.webmaker.org/t/testing-1-reading-for-the-web/1149

Would love help writing the reflection prompts we want our testers to riff on. 

Let's build from #88 & #79

**Comment by dajbelshaw** [comment]
Perhaps we make this two threads, mirroring the pre- and post-activity questionnaires? We could link out to them, but capture more informal stuff in the threads themselves - e.g. just ask *What was the biggest "aha" moment for your learners during the activity?*

Would that work?

**Comment by ldecoursy** [comment]
I think to keep things simple (and to lessen the link load) we should have one thread for reflection after the activity has been tested. Other possible prompts:
* Please share any anecdotes/quotes from your learners about the activity.
* Were there any points along the way where you or your learners got stuck?
* Did you end up having to alter or remix any of the instructions?
* Would you want to run this activity again?

**Comment by dajbelshaw** [comment]
Cool. Perhaps we should encourage tip-sharing beforehand in the general Chat area of the forum. :)

**Comment by thornet** [comment]
Shipped.
