### ISSUE TITLE
Make questionnaire for Reading the Web: Web Mechanics (Ping Kong)

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/webmaker-curriculum#133]
Linked to learning objectives here:  https://github.com/mozilla/webmaker-curriculum/issues/124

Draft pre-activity Q's:
* How comfortable do you think learners are with reading, evaluating and manipulating URLs? (open ended)
* How might learners distinguish between URLs, IP addresses and simple search terms? (open ended)
* Do you think learners understand that there is a difference between the web and the Internet? (y/n)

I know @smithisgeneric is out today and Monday. @dajbelshaw @thornet let me know what you think. Can someone take a stab at the post-Q's?

**Comment by dajbelshaw** [comment]
Yep, I'd only suggest a couple of slight tweaks @ldecoursy (bolded):

* How comfortable do you think learners are with reading, evaluating and manipulating URLs? **(scale: 1-5)**
* How **did** learners distinguish between URLs, IP addresses and simple search terms? (open ended)
* Do you think learners **now** understand that there is a difference between the web and the Internet? (y/n)

:smiley_cat:

**Comment by ldecoursy** [comment]
Here's the link to the form for the pre-activity questionnaire: http://goo.gl/forms/i58qZA1PTl
@thornet ready for adding to the lovely testing landing page ;)

@dajbelshaw @thornet Thoughts on these for POST-activity questions?
* How comfortable do you think learners are with reading, evaluating and manipulating URLs? (scale: 1-5)
* Are your learners more easily able to distinguish between URLs, IP addresses and simple search terms? (open ended)
* Can your learners understand and articulate the difference between the web and the Internet? (y/n and a box to specify?)

**Comment by dajbelshaw** [comment]
Looks good to me, @ldecoursy. We should explain in the intro that these are very similar questions to ascertain whether the session has had the desired impact. As part of that, we should ask mentors to be brutally honest!

**Comment by thornet** [comment]
Thanks, @dajbelshaw ! Adding pre questionnaire to our pages. 

Could you write the post-questionnaire to be more tied to the Ping Kong activity, like http://goo.gl/forms/ezm6IXWhhM?

**Comment by dajbelshaw** [comment]
OK, let's try this for the post-questionnaire. In hindsight, we may need to change the pre-activity to be more like [the Kraken one](https://docs.google.com/a/mozillafoundation.org/forms/d/190bYzX-O1FvtwgxWrsp0WxvkUMqIh_tIx0dAb0f5dVo/formResponse). :)

# Reading the Web: Web Mechanics (post-activity)
Thanks for testing the activities for Web Literacy Clubs! Please complete the following three questions after you tested the Ping Kong activity with your learners.

## 1) Which of the following terms do you think *most* of your learners could now define?
Tick all that apply: 
* [ ] Command line/Command Prompt
* [ ] Hop
* [ ] Internet Protocol (IP) Address
* [ ] Internet Service Provider (ISP)
* [ ] Web Server
* [ ] Local Area Network (LAN)
* [ ] Packet
* [ ] Ping
* [ ] Router
* [ ] Trace Route

## 2) How did your learners' understanding of how the Internet works change as a result of this activity?
[paragraph text response]

## 3) Was the Ping Kong activity an effective way to engage learners in understanding the basic mechanics of the web?
[drop-down response]
* Highly agree
* Agree
* Neutral
* Disagree
* Highly disagree
* Unsure 
* Not applicable/did not attempt

## Contact details
Thanks! To complete the survey press 'Submit' below. You are welcome to remain anonymous, but sharing your name/email/location allows us to follow-up if needed. 

Name

Email

Location

**Comment by ldecoursy** [comment]
Looks good to me :) I just gave @dajbelshaw and @thornet editing access to the pre Ping Kong survey in case you want to make any edits. Do you need me to port the above into a Google Form? Let me know either way.

**Comment by thornet** [comment]
Thanks,@dajbelshaw! Yes, liking those q's and if you want to modify the pre questionnaire, we've got a few hours to do that. Because of time, would it be alright @dajbelshaw to turn this into a quick form? Then I'll add it to the right testing pages.

**Comment by dajbelshaw** [comment]
Yes please, @ldecoursy - would be good if you could port this into a Google Form please. :+1: 

*(made the smallest of edits to the pre- survey Form: added 'your' to each question for clarification)*

**Comment by dajbelshaw** [comment]
Yep, I'll do that this afternoon.

**Comment by dajbelshaw** [comment]
OK, done: http://goo.gl/forms/qy6UZiySfF

Saw that someone added a *Details about your testing group* page in the Credibility post-questionnaire, so that's in this one too. :)

**Comment by thornet** [comment]
Thanks! Adding to the pages.
