### ISSUE TITLE
Create activity for 2. Writing for the Web: Remixing

### ISSUE THREAD

**Issue by thornet** [mozilla/webmaker-curriculum#134]
This is our sweet spot! 

Let's gather ideas and existing assets for an 45min. activity that teaches some flavor of: 

* Modifying existing web resources to create something new
* Identifying and using openly-licensed work
* Combining multimedia resources
* Creating something new on the web using existing resources

-----
Update by @dajbelshaw: after discussion with community we now have learning objectives (#136):

* Identify openly-licensed resources
* Curate openly-licensed resources in different media
* Combine openly-licensed resources to create something new on the web

Discussing this with community in [this Discourse thread](discourse.webmaker.org/t/curating-curriculum-composing-for-the-web/1167/).

**Comment by dajbelshaw** [comment]
Excellent, filed Issue #136 to create learning objectives from these skills. :)

**Comment by dajbelshaw** [comment]
Throwing these in here from the Webmaker resources section for Remixing:
* [X-Ray Goggles teaching kit](https://mozteach.makes.org/thimble/xray-goggles-teaching-kit)
* [Meme generator](https://thimble.webmaker.org/project/59455/remix) (uses Thimble)
* [Animated GIF Generator](https://imgflip.com/gifgenerator)
* [The Gendered Advertising Remixer](http://www.genderremixer.com/)

:thought_balloon: The advertising remixer would be a great starter activity: easy to use, makes the point, and provokes discussion!

**Comment by thornet** [comment]
Going to make this page tomorrow based on: http://discourse.webmaker.org/t/curating-curriculum-remixing/1168/8

**Comment by dajbelshaw** [comment]
I'm happy to take one of these (this or #135) and make a start.

**Comment by dajbelshaw** [comment]
I reckon we're done: https://mozilla.github.io/webmaker-curriculum/WebLiteracyBasics-I/session02-hackthenews.html

\o/
