### ISSUE TITLE
Create activity for 2. Writing for the Web: Composing for the Web

### ISSUE THREAD

**Issue by dajbelshaw** [mozilla/webmaker-curriculum#135]
We've got the learning objectives for this from Issue #111:

* Summarize the most commonly-used HTML tags
* Use HTML tags to re-structure a web page
* Create a web page for a specific audience 

-----
**Update:** finalised learning objectives (above) and asking community for input in [this thread](discourse.webmaker.org/t/curating-curriculum-composing-for-the-web/1167/)

**Comment by thornet** [comment]
Going to create this page tomorrow based on Discourse thread: http://discourse.webmaker.org/t/curating-curriculum-composing-for-the-web/1167/10?u=michelle

**Comment by dajbelshaw** [comment]
I'm happy to take one of these (this or #134) and make a start.

**Comment by dajbelshaw** [comment]
Done! https://mozilla.github.io/webmaker-curriculum/WebLiteracyBasics-I/session02-puzzlebox.html

:+1:
