### ISSUE TITLE
Create questionnaires for 2. Writing for the Web: Composing for the Web

### ISSUE THREAD

**Issue by dajbelshaw** [mozilla/webmaker-curriculum#137]
We need pre- and post-session surveys for this once we've decided on the activities (#135)

-----
**Update:**
* Pre-session questionnaire (Mentors): http://goo.gl/forms/ejKUx696cB
* Post-session questionnaire (Mentors): http://goo.gl/forms/QqCRZzIHjk
* Pre-session questionnaire (Learners): http://goo.gl/forms/Vkk4f2fAEC
* Post-session questionnaire (Learners): http://goo.gl/forms/UzULI6RUpy

**Comment by dajbelshaw** [comment]
Paging @smithisgeneric to see if she use her expertise to come up with the questions for this (which I can then copy to Google Forms)?

**Comment by smithisgeneric** [comment]
Here are some suggestions: 

Pre: 

Do your learners have experience with HTML?
Yes 
No
Unsure

What HTML tags do you expect will be most interesting for your learners? 

What challenges do you expect your learners to have with HTML? 

Post 

Were the activities effective ways to engage learners to understand HMTL? 
Highly Agree
Agree
Neutral
Disagree
Unsure 
Not applicable/did not attempt 

What challenges did your learners have with HTML?    

Which of the following skills did at least 70% of your learners demonstrate through the activities.  Please select all that apply.  
Utilizing opening and closing tags
Using tags to format text
Using tags to insert an image
Using tags to insert a hyperlink
Using tags to create a list with numbers or bullets
Creating a simple webpage from scratch 

cc: @dajbelshaw

**Comment by dajbelshaw** [comment]
Cool, thanks @smithisgeneric. Will convert this to a Google Form. :)

**Comment by dajbelshaw** [comment]
Pre-session questionnaire: http://goo.gl/forms/ejKUx696cB

**Comment by dajbelshaw** [comment]
Post-session questionnaire: http://goo.gl/forms/QqCRZzIHjk

**Comment by thornet** [comment]
Thanks, all! 

Claw has also requested pre & post questionnaires for learners. Could we quickly generate those as well?

**Comment by dajbelshaw** [comment]
Happy to create questionnaires, but will just point out that this activity doesn't require a computer. Are we expecting mentors to get learners to fill in computer-based questionnaire, or would it be better on paper?

/ cc @thornet @ldecoursy

**Comment by dajbelshaw** [comment]
OK, well online or offline we need some questions for learners :

# Pre

## Question 1

How much experience do you have with HTML, the language of the web?
_[scale]_

## Question 2

Would you be able to explain what these HTML tags are for? `<p>, <img>, <body>`?
_[multiple choice]_
- Yes
- No
- Unsure

## Question 3

Can you give examples of a website that is aimed at you, and one that is aimed at someone else?
_[paragraph text]_

# Post

## Question 1a

Did you find the activities interesting?
_[scale]_

## Question 1b

Did you find the activities fun?
_[scale]_

## Question 2

Would you now be able to explain to someone else what HTML tags do?
_[multiple choice]_
- Yes
- No
- Unsure

## Question 3

Explain some ways that websites are structured to appeal to different audiences.
_[paragraph text]_

---

/ cc @thornet @ldecoursy

**Comment by dajbelshaw** [comment]
Pre-session questionnaire for learners: http://goo.gl/forms/Vkk4f2fAEC

**Comment by dajbelshaw** [comment]
Post-session questionnaire for learners: http://goo.gl/forms/UzULI6RUpy

**Comment by dajbelshaw** [comment]
@thornet could you close this once you've transferred the questionnaires to the [index page](https://mozilla.github.io/webmaker-curriculum/WebLiteracyBasics-I/), please?

**Comment by dajbelshaw** [comment]
Done!
