### ISSUE TITLE
 Create questionnaires for 2. Writing for the Web: Remixing 

### ISSUE THREAD

**Issue by dajbelshaw** [mozilla/webmaker-curriculum#138]
Once we've got the learning objectives (#136) and activities (#134) for Remixing, we need pre- and post- session questionnaires! 

-----
**Update:**

* Pre-session questionnaire for Mentors: http://goo.gl/forms/OMqDnKtcvH 
* Post-session questionnaire for Mentors: http://goo.gl/forms/RWJlvdrS0k 
* Pre-session questionnaire for Learners: http://goo.gl/forms/yEdD8MQ8Cn
* Post-session questionnaire for Leaners: http://goo.gl/forms/sr3KzghBsF

**Comment by dajbelshaw** [comment]
Paging @smithisgeneric to see if she use her expertise to come up with the questions for this (which I can then copy to Google Forms)?

**Comment by smithisgeneric** [comment]
Here are some suggestions: 

Pre

Do your learners have experience with remix?
Yes 
No
Unsure

If yes, what kind of remixes have your learners created? 

What challenges do you expect your learners to have with remix?  

Post 

Which of the following skills did at least 70% of your learners demonstrate?
-   Using an appropriate search strategy to find openly licensed work
-   Finding Creatives Commons Licensed work
-   Finding alternative openly licensed work (i.e., content in the public domain) 
-   Exploring the license terms of openly licensed work to better understand it
-   Combining openly licensed works to make something new
-   Adding their own original content to openly licensed work to create a remix
-   Combining multiple learner created content to make a remix (i.e., Sarah’s images plus Zack’s audio)  

What discussion points or questions emerged about remix during the activities?     

Were the activities effective ways to engage learners to understand remix? 
Highly Agree
Agree
Neutral
Disagree
Unsure 
Not applicable/did not attempt 

cc: @dajbelshaw

**Comment by dajbelshaw** [comment]
Thanks @smithisgeneric! Will get these converted into a Google Form. :)

**Comment by dajbelshaw** [comment]
Pre-session questionnaire for Mentors: http://goo.gl/forms/OMqDnKtcvH

**Comment by dajbelshaw** [comment]
Post-session questionnaire for Mentors: http://goo.gl/forms/RWJlvdrS0k

**Comment by thornet** [comment]
Thanks, all! 

Claw has also requested pre & post questionnaires for learners. Could we quickly generate those as well?

**Comment by dajbelshaw** [comment]
OK then, for leaners, how about....

# Pre

## Question 1

Do you know what it means to 'remix' something?
_[scale]_
- Yes
- I think so
- Not sure
- Probably not
- No

## Question 2

Have you remixed something on the Web before?
_[radio buttons]_
- Yes
- No
- Unsure

## Question 3

Explain what you think 'openly licensed' resources are.
[paragraph text]

# Post

## Question 1a

Did you find the activities interesting?
_[scale]_

## Question 1b

Did you find the activities fun?
_[scale]_

## Question 2

Do you now know what it means to 'remix' something?
_[scale]_

## Question 3

Explain what 'openly licensed' resources are and how you used them in the session.
_[paragraph text]_

**Comment by dajbelshaw** [comment]
Pre-session questionnaire for Learners: http://goo.gl/forms/yEdD8MQ8Cn

**Comment by dajbelshaw** [comment]
Post-session questionnaire for Leaners: http://goo.gl/forms/sr3KzghBsF

**Comment by dajbelshaw** [comment]
Need QA from @thornet & @ldecoursy 

Also, wondering whether we're 'keeping responses in Forms' or creating spreadsheet. Which option did you choose, Lainie?

**Comment by ldecoursy** [comment]
These look good to me - think we have the responses going directly into a spreadsheet for easier viewing...

**Comment by dajbelshaw** [comment]
Cool, will update them all and give you and @thornet edit permissions, @ldecoursy :)

**Comment by dajbelshaw** [comment]
@thornet could you close this once you've transferred the questionnaires to the [index page](https://mozilla.github.io/webmaker-curriculum/WebLiteracyBasics-I/), please?

**Comment by dajbelshaw** [comment]
Done!
