### ISSUE TITLE
Reword "do activity on your own" in index.html

### ISSUE THREAD

**Issue by thornet** [mozilla/webmaker-curriculum#139]
Per @jgmac1106's good feedback in the club call. That phrase was confusing. Maybe "practice the activity on your own."

**Comment by dajbelshaw** [comment]
Maybe we need to separate the four bullets into Before / During / After as well?

## Before
* *Fill in* pre-activity questionnaire
* *Run through* the activity to *familiarise* yourself *with it*

## During
* *Complete* the activity with your learners

## After
* *Fill in* post-activity questionnaire

**Comment by dajbelshaw** [comment]
Updated: https://github.com/mozilla/webmaker-curriculum/commit/af8336c44ad1e6996d0ac083f48aecb7b017b147
