### ISSUE TITLE
Determine which badges (if any) to issue in Q1

### ISSUE THREAD

**Issue by thornet** [mozilla/webmaker-curriculum#140]
Let's make a decision whether we want to issue any of our existing badges to the Q1 cohort of testers and learners. This would be to acknowledge participation.

**Comment by dajbelshaw** [comment]
Perhaps we should issue the following three directly:

<a href="https://webmaker.org/badges/event-host"><img width="100px" src="https://badgekit-mozilla.mofoprod.net/images/badge/259" alt="Event host">Event host

<a href=""><img width="100px" src="https://badgekit-mozilla.mofoprod.net/images/badge/961" alt="Web Literacy skill sharer">Web Literacy skill sharer 

<a href="https://webmaker.org/badges/teaching-kit-remixer"><img width="100px" src="https://badgekit-mozilla.mofoprod.net/images/badge/960" alt="Teaching kit remixer">Teaching kit remixer

We could then encourage testers to apply for the following if they feel they or their learners have met the criteria. The carrot would be that if they earn the Webmaker Mentor badge, they can issue these directly themselves! :)

<a href="https://webmaker.org/badges/webmaker-mentor"><img width="100px" src="https://stuff.webmaker.org/badges/webmaker-mentor.png" alt="Webmaker Mentor">Webmaker Mentor

<a href="https://webmaker.org/badges/credibility-maker"><img width="100px" src="https://badgekit-mozilla.mofoprod.net/images/badge/943" alt="Credibility Maker">Credibility Maker

<a href="https://webmaker.org/badges/web-mechanics-maker"><img width="100px" src="https://badgekit-mozilla.mofoprod.net/images/badge/389" alt="Web Mechanics Maker">Web Mechanics Maker

**Comment by dajbelshaw** [comment]
Just revisiting this and thinking about whether we want to create a couple of non-linear pathways. We could do this with the badges we've already got, but we might want to think about the points at which we'd want to acknowledge/encourage contribution:

![Mentor pathway](https://cloud.githubusercontent.com/assets/2429426/6021217/f3ca1ddc-abab-11e4-9fdc-2a0f23736e65.png)

This is just a starter for ten. Glyphs aren't very indicative - just thinking aloud!

_A) Webmaker Club Mentor
B) [Teaching Kit Remixer](https://webmaker.org/badges/teaching-kit-remixer)
*C) Webmaker Clubs advocate_
D) [Web Literacy Skill Sharer](https://github.com/mozilla/webmaker-curriculum/issues/140)
E) [Open Practices Maker](https://webmaker.org/badges/open-practices-maker)

\* Those _in italics_ indicate badges that don't currently exist.

This should allow a clear progression to the [Webmaker Mentor badge](https://webmaker.org/badges/webmaker-mentor) in a Clubs context.

**Comment by thornet** [comment]
Moved to Mozilla Learning repo.
