### ISSUE TITLE
Create questionnaires for 3. Participating on the Web: Open Practices

### ISSUE THREAD

**Issue by dajbelshaw** [mozilla/webmaker-curriculum#145]
We need questionnaires for this once the activities are finalised (#144)

To do:
- [x] [Pre-session questionnaire for Learners](http://goo.gl/forms/4DanIgrM9w)
- [x] [Post-session questionnaire for Learners](http://goo.gl/forms/ZeyNYQzc1t)
- [x] [Pre-session questionnaire for Mentors](http://goo.gl/forms/J1fsuwZEgs)
- [x] [Post-session questionnaire for Mentors](http://goo.gl/forms/uOEzAbbH34)

**Comment by dajbelshaw** [comment]
Hey @smithisgeneric. I'll be on PTO next week, so just wondering if you want a hand with these _this_ week? If not, when you've finished please let @ldecoursy know so she can add to Google Forms. :)

**Comment by smithisgeneric** [comment]
@dajbelshaw can you please take this on this week.   

In general for issues like this as part of the work flow for Webmaker clubs curriculum please note that I can provide consultation on questions only in my current role. @dajbelshaw, please do not assign responsibility to me  for questionnaires. I can provide consultation on appropriate questions only.

**Comment by dajbelshaw** [comment]
Yes, of course @smithisgeneric - my apologies. Will draft questions this week. :)

**Comment by dajbelshaw** [comment]
Got these done and in Google Forms as both @ldecoursy and I are on PTO next week! May need some tweaking by @thornet.
