### ISSUE TITLE
Move all tickets in this repo to Mozilla-Learning

### ISSUE THREAD

**Issue by thornet** [mozilla/webmaker-curriculum#152]
Our new team repo: https://github.com/MozillaFoundation/Mozilla-Learning/labels/curriculum

**Comment by thornet** [comment]
@LauraHilliger @dajbelshaw mind taking a look at tickets in this repo you want to make sure we keep, and then just move them over? 

Am doing that now for mine. 

Will close this issue at the end of the week and we won't use this repo for tracking issues anymore.

**Comment by dajbelshaw** [comment]
Yep, will do @thornet. Apologies, must have missed the switch in my post-PTO catch-up haste!

**Comment by LauraHilliger** [comment]
#onit

**Comment by dajbelshaw** [comment]
Looks like there's no 'official' way to move issues, but you can use this: https://github-issue-mover.appspot.com (which uses the GitHub API)
