### ISSUE TITLE
Write learning objectives for Session 1

### ISSUE THREAD

**Issue by dajbelshaw** [mozilla/webmaker-curriculum#17]
Use this: http://ccoe.rbhs.rutgers.edu/forms/EffectiveUseofLearningObjectives.pdf

**Comment by dajbelshaw** [comment]
Done, but would appreciate review by @LauraHilliger

**Comment by LauraHilliger** [comment]
Works for me! We should include in the wiki from #64 the process of taking the WebLit skills under a competency and building out objectives from the skills. Nice work Doug!
