### ISSUE TITLE
simplify course in a box for displaying our io pages

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/webmaker-curriculum#32]
Later this year, we want to remix @p2pu's course in a box to present curriculum that has been tested and iterated upon. But we know that the repo might be overwhelming to some folks, so we'd like to simplify it as much as possible before spending time adjusting the style using Maker strap and dumping read me files into the structure.

http://howto.p2pu.org/

**Comment by dirkcuys** [comment]
Hey @LauraHilliger - I agree that I want Jekyll to be simpler. 

One complexity that I would really like to avoid is where users need to make 2 updates to do 1 thing. For instance, to create a new module a user need to create a folder in the modules directory and add that module name in _data/course.yml.

What are the places where you would like things to be simpler - I can use help identifying them :)

**Comment by LauraHilliger** [comment]
Hey @dirkcuys I'm happy to help you think about this! Having to update multiple places can definitely be confusing and frustrating, so +1 to that suggestion. 

Another thing that would help a lot would be if Jekyll/Course-in-a-box could "hide" things a little. If I'm an educator, or Github n00b, and I look at that repo, I might be overwhelmed by the 11 folder plus files and whatever is inside all of them. What things could a n00b ignore? An educator, for example, probably won't need to look inside the JS folder if they're only dealing with content. (How come _sass and css are separate? What does that underscore distinguish anyway?

The hard part for all of this (for non-devs, I guess) is finding the places where you can remix something and trusting yourself with github (which is my big problem - I wanted to remix CIB for curriculum, got stuck with merge conflicts, reversed my ideas/ambitions and filed this bug :) 

As I play, if something else pops up, I'll let you know!

**Comment by dirkcuys** [comment]
It may not be a jekyll solution, but if you use prose.io for editing you can hide folders. Try going to prose.io and open course in a box. You can do this for any gh-pages repo in the _config file, see https://github.com/p2pu/course-in-a-box/blob/gh-pages/_config.yml#L20-L28. Only works if you edit in prose.io

Merging is a big challenge. Ideally content editors would never get conflicts, but when they do the wheels does come off :( My only solution to that so far is to encourage people to ask for help when they get stuck

**Comment by dajbelshaw** [comment]
Can we close this now, @LauraHilliger? If not, could you add a milestone please? :)

**Comment by LauraHilliger** [comment]
moving to Mozilla-Learning repo and closing this issue.
