### ISSUE TITLE
apply maker strap to course in a box

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/webmaker-curriculum#33]
see issue 32 as this is related

**Comment by dirkcuys** [comment]
Adding maker strap should be fairly easy - we drew a lot of inspiration from it :) The most work would probably be updating the navigation HTML

**Comment by dajbelshaw** [comment]
Can we close this issue now? If not, could you add a milestone please, @LauraHilliger? :)

**Comment by LauraHilliger** [comment]
closing as I assume the wm Engineering team will be #onit in https://github.com/MozillaFoundation/Mozilla-Learning/issues/72
