### ISSUE TITLE
update graphic to match new curricular structure

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/webmaker-curriculum#34]

**Comment by LauraHilliger** [comment]
We need to remix our own meta arc for WebLitBasics and the graphic as well. Meta structure will be:

Module: WebLiteracyBasics #
Session 1: Exploring: Reading the Web: (main competency we're focusing on)
Session 2: Building: Writing the Web:
Session 3: Participating: Participating on the Web:

**Comment by dajbelshaw** [comment]
New roadmap in #97

**Comment by LauraHilliger** [comment]
moved to https://github.com/MozillaFoundation/Mozilla-Learning/issues/92 and closing
