### ISSUE TITLE
Update "Club Audit" with a curriculum audit

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/webmaker-curriculum#40]
Might be useful to look at the clubs being audited and auditing their curriculum at the same time. Might even find something we could use:

https://docs.google.com/a/zythepsary.com/spreadsheets/d/1JvIm1nAVBqtbOTwEpwzc_WyGL11Sx3QG5zSGUy1SQk8/edit#gid=0

**Comment by dajbelshaw** [comment]
Who's on point for this? @simonaramkisson? :)

**Comment by LauraHilliger** [comment]
moved to https://github.com/MozillaFoundation/Mozilla-Learning/issues/93
