### ISSUE TITLE
Build grid design for v1 of presentation

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/webmaker-curriculum#45]
After much debate and thought, we've decided to build a simple html/css site hosting the curriculum. Activities/Resources will continue to utilize the activity template. 

We'll use @iamjessklein's playlist mockup from July to improve on existing teaching kits. We can A/B test language here as well: 

Grid/Design to be built:
https://www.flickr.com/photos/jessicaklein/14499321420/

**Comment by dajbelshaw** [comment]
Just to be clear, is this right?

- use GitHub pages to host the curriculum
- use Thimble for the activity templates

<3 Jess' mockup.

**Comment by LauraHilliger** [comment]
nope, sorry I wasn't clear enough. 

We'll use github pages to host the curriculum, full stop. The difference is **instead** of using [this kit design + html/css](https://mozteach.makes.org/thimble/make-your-own-teaching-kit
), we'll build Jess's mockup. Activity template (e.g. [this one](https://mozteach.makes.org/thimble/make-your-own-teaching-activity)) will stay the same for now.

**Comment by dajbelshaw** [comment]
Cool, thought that was what we decided! Just checking. :-)

**Comment by LauraHilliger** [comment]
PR #48
