### ISSUE TITLE
Content review

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/webmaker-curriculum#51]
@keyboardkat @omnignorant - I'm super ready for some feedback!

Would love to have some feedback and ideas on the 1st session for the Clubs Curriculum. This is a  remix of the Kraken activity, basically made into  a teaching kit for Clubs (using the new design from #45 )

Can you two take a look, share any thoughts and give me some ideas for the "Remixing Context" section? Just update this issue with your thoughts :)

http://mozilla.github.io/webmaker-curriculum/WebLiteracyBasics-I/session01-credibility.html

@dajbelshaw is working on Learning objectives in #17 (hence the Cupcake Ipsum)

**Comment by omnignorant** [comment]
Hey Laura, just had a glance. Obs looks amazing! But I'll need to dig in to say something meaningful. What's the deadline for some feedback? We're scrambling for our big event next week and would like to push as many commitments into the 2nd half of January as possible.
