### ISSUE TITLE
Create wiki page on how to write Learning Objectives

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/webmaker-curriculum#64]
At the moment we're pointing people to [this great resource](http://ccoe.rbhs.rutgers.edu/forms/EffectiveUseofLearningObjectives.pdf), but we should simplify it and put it inside the wiki in this repo.

**Comment by dajbelshaw** [comment]
Will be writing this here: https://github.com/mozilla/webmaker-curriculum/wiki/How-to-write-Learning-Objectives

**Comment by dajbelshaw** [comment]
OK, would appreciate a review from @LauraHilliger and @smithisgeneric before proceeding further. Have a look at this: https://github.com/mozilla/webmaker-curriculum/wiki/How-to-write-Learning-Objectives

**Comment by LauraHilliger** [comment]
looks great. I would add examples under blooms headers, probably will help folks (who aren't edunerds) to understand.

**Comment by dajbelshaw** [comment]
Thanks @LauraHilliger, have added examples under each part of Blooms

**Comment by iamjessklein** [comment]
Nice first stab @dajbelshaw 
I suspect that it would be useful if there was some kind of tagging system that either built off of Blooms or was a recommended tag so that it would be possible to filter like-minded learning objectives. If anything, possibly just indicating that people should tag the learning objectives with the Web Literacy that they are trying to help develop.

**Comment by dajbelshaw** [comment]
Thanks @iamjessklein! I think there was a bug assigned to @toolness in Bugzilla a while back that talked about Beginner / Intermediate / Advanced. We also might want to start tagging by skill?

All of this is grist for the Web Literacy Map v1.5 community calls - starting tomorrow! https://wiki.mozilla.org/Webmaker/WebLiteracyMap/v1.5

**Comment by dajbelshaw** [comment]
Closing this as it does the job for the time being: https://github.com/mozilla/webmaker-curriculum/wiki/How-to-write-Learning-Objectives

Tag-based approach that @iamjessklein mentions should perhaps be included in Issue #74 - which could use some feedback! :)
