### ISSUE TITLE
Add a "Remix" or "View on GiHub" button to github.io pages

### ISSUE THREAD

**Issue by omnignorant** [mozilla/webmaker-curriculum#65]
For folks who are somewhat new to GitHub, or just lazy like me, maybe we should have some nice buttons on all our stuff that links back to this repo, or sub directories of it, etc.

Having tooled around with GitHub over the Xmas break, I'm also wondering if it wouldn't make sense to make each Unit a separate repo... or a sub-repo (forget what that's called). Feels like overkill to have to fork the entire webmaker-curriculum in order to customize one bit of it.

**Comment by dajbelshaw** [comment]
Definitely +1 to buttons. We should test what works best for people - in terms of colours, iconography, etc.

In terms of separate repos, I would suggest we keep it simple and just to one for now. Perhaps we can then ask users if they're frustrated at having to fork the whole thing. Simplicity FTW!

**Comment by LauraHilliger** [comment]
I added a header to the pages: http://mozilla.github.io/webmaker-curriculum/WebLiteracyBasics-I/session01-credibility.html

Thoughts?

**Comment by dajbelshaw** [comment]
I think it's looking amazeballs. Any more on the design front would be gilding the lily for testing, IMO.

**Comment by iamjessklein** [comment]
This looks great, particularly for testing.
My comment about the buttons might be just that they aren't high contrast enough on hover, but really that doesn't seem to be impeding testing this out. 

I would take a look at the "pledge" button - as it is floating when I resize the browser.

**Comment by LauraHilliger** [comment]
Closing for now. We should talk design cleanup though. It's using MakerStrap styles (e.g. the hover color). And the floating btn is covered, I think in #100 

Also filed #115 for hiccups in my crappy code :computer:
