### ISSUE TITLE
Template 'reflect and review' section

### ISSUE THREAD

**Issue by dajbelshaw** [mozilla/webmaker-curriculum#73]
Individual assessment
Peer assessment
Expert assessment

**Comment by dajbelshaw** [comment]
Will be writing here: https://github.com/mozilla/webmaker-curriculum/wiki/Reflect-and-Review

**Comment by dajbelshaw** [comment]
On second thoughts, although I'll build it out on the wiki, this should probably be transferred to a shinier github.io page. What do you think, @LauraHilliger?

**Comment by LauraHilliger** [comment]
Both? Wiki for the explanation of what that section IS and why it's important, and the section on each overview page (e.g. http://mozilla.github.io/webmaker-curriculum/WebLiteracyBasics-I/session01-credibility.html ) implementing the template

Can we come up with more accessible ways to say "individual" "peer" and "expert" "assessment"? Assessment sounds so nerdy...maybe we can have some fun language? I like fun. @keyboardkat any ideas for renaming those three pieces?

**Comment by dajbelshaw** [comment]
Oh yeah, absolutely, they're just placeholders. I'll build it out on the wiki, and then it can be fun-ified. ;)

**Comment by dajbelshaw** [comment]
OK, more content needed, but first draft: https://github.com/mozilla/webmaker-curriculum/wiki/Reflect-and-Review

/ cc @LauraHilliger

**Comment by LauraHilliger** [comment]
I added a link to discourse to this page, but also filed #96

@keyboardkat Can you think of fun ways to say:

Individual assessment
Peer assessment
Expert assessment

Would go under review and reflect, as headers to the bullet points on: http://mozilla.github.io/webmaker-curriculum/WebLiteracyBasics-I/session01-credibility.html

**Comment by dajbelshaw** [comment]
Would also be good to feature that on the [Reflect and Review](https://github.com/mozilla/webmaker-curriculum/wiki/Reflect-and-Review) section of the wiki.

**Comment by dajbelshaw** [comment]
Do we actually still need this? Perhaps each activity has a bespoke Reflect & Review section?

**Comment by dajbelshaw** [comment]
Closing this as it's probably not needed any more.
