### ISSUE TITLE
Create wiki page for remixing this curriculum

### ISSUE THREAD

**Issue by dajbelshaw** [mozilla/webmaker-curriculum#74]
Currently, users are encouraged in the overview page to remix the page. Perhaps this should be behind a remix button?

**Comment by LauraHilliger** [comment]
yes, I think so. We should "separate out remixing of activities from the overview page" - build a "remix this activity" button in, and take it to the Wiki. Editing this issue title.

**Comment by dajbelshaw** [comment]
Writing this here: https://github.com/mozilla/webmaker-curriculum/wiki/How-to-remix-Webmaker-Club-activities

**Comment by LauraHilliger** [comment]
@dajbelshaw and I chatted quickly and decided to make a "How to Remix Context" training module. [We've filed that issue in the Webmaker Training Repo](https://github.com/mozilla/school-of-webmaking/issues/240)

In the meantime, I've edited the name and @dajbelshaw has already [drafted the wiki](https://github.com/mozilla/webmaker-curriculum/wiki/How-to-remix-Webmaker-Club-activities). Adding QA tag for @keyboardkat's review of that page.

**Comment by dajbelshaw** [comment]
Awaiting @keyboardkat's response before closing this. Happy for others to weigh in too!
