### ISSUE TITLE
Flesh out Remixing Context section for Club Types

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/webmaker-curriculum#78]
Would love to have more input on how you might remix [Session 1 (Credibility)](http://mozilla.github.io/webmaker-curriculum/WebLiteracyBasics-I/session01-credibility.html) for specific club types.

**Comment by LauraHilliger** [comment]
we should move the remixing context section to the github wiki and provide examples related to the individual activities.

**Comment by dajbelshaw** [comment]
+1 

However, I do like the idea of a hidden drop-down revealed on click which talks about lightweight remixing for different types of clubs (GLAM, etc.)

**Comment by LauraHilliger** [comment]
I added a bit to this page, but we could build this out a bit. Examples might be the best way, we should ask folks already running clubs/teaching the web how they remix context and take notes! 

https://github.com/mozilla/webmaker-curriculum/wiki/How-to-remix-Learning-Activities

**Comment by jgmac1106** [comment]
You can remix the content and the context:
- Content-Change the Kraken to another local legend or myth. OR  Differentiating based on age: requirement "Is it real or is it not", is developmentally appropriate for younger grades but may not be enough for older clubs. For example some one might add a bit about, Now go investigate the author of your credible sources. What makes her an expert.
- Context-How much tech access do they have? Is it 1:1? Is it mobile only? Do your clubs meet for a 1/2 or hour. That would be a context change. Add in different metacognitive prompts (is this a content remix or a context remix...having difficulty differentiating): The Kraken included: identify author, currency, and design. I might want to change the credbility markers students look for.

**Comment by thornet** [comment]
For remixing at this stage, we might prompt most testers to remix in writing, rather than editing in Github. 

I'd love to guide testers to share their remixes on this thread: http://discourse.webmaker.org/t/testing-1-reading-for-the-web/1149 

(see issue #130)

@jgmac1106: love the examples you gave! Would you be up for modeling those as a reflection in the Discourse thread?

**Comment by dajbelshaw** [comment]
Do you mean 'remix in writing' and then get us to edit the HTML, @thornet? or...?

**Comment by jgmac1106** [comment]
@thornet Sure. I can post a reflection about how I did some basic remixing if this what you are asking.

I also agree with @thornet the first web literacy basic around remixing should stay far away from code and even further from github. It should be either image based or changing text on website using X-Ray Goggles.

**Comment by dajbelshaw** [comment]
Ah, +1 to X-Ray Goggles!

**Comment by jgmac1106** [comment]
@thornet Do you mean a reflection like something like this: http://writingwhilethrowing.tumblr.com/post/108886858443/remixing-making-of-a-zeega

I can post it to discourse, I like the idea of focusing on images for remixing.

but  like @dajbelshaw I like the idea of X-Ray Goggles as Remix 1: (though offline would be hard).

I know the coding crowd pushes back when X-Ray Goggles is used when just changing texts but I find the workflow to start with:
- text
- images (this is the bridge to code)
- code

**Comment by thornet** [comment]
+1 @jgmac1106 to those kinds of remixes, and even if that's too technical/high-bar, it can be narrative. "I changed the Kraken to be the Lock Ness monster for my local context. "

**Comment by dajbelshaw** [comment]
Works well! http://dajbelshaw.makes.org/goggles/dajbelshaws-remix-of-web-literacy-basics-1-reading-the-web-kraken-the-code 

(URL seems to indicate some kind of URL issue though?)

**Comment by jgmac1106** [comment]
I apologize for miss reading the ticket issue. I thought we were working on a basic remixing activity and not the remixing context ticket for credibility.

**Comment by dajbelshaw** [comment]
Not a problem @jgmac1106 - thanks for your input! And you're welcome to open new tickets. ;)

**Comment by thornet** [comment]
@jgmac1106 sorry for the confusion. yes, we'll have a section to design the activities that teach remix soon. learning how to use github for this project = a good experiment!

@dajbelshaw: will defer to you if we still want to flesh out this section in the wiki. I think we can illustrate what we mean in the Discourse thread to a lot of effect: http://discourse.webmaker.org/t/testing-1-reading-for-the-web/1149

**Comment by dajbelshaw** [comment]
Agree @thornet - let's just use Discourse and build out the wiki if there's a need (perceived/requested)
