### ISSUE TITLE
Make questionnaire for Reading the Web: Credibility (Kraken the Code activity) 

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/webmaker-curriculum#79]
@smithisgeneric is on tap to create pre and post questionnaires for Club Curriculum Testers. The objectives were written with #17 and are included on the [session overview page](http://mozilla.github.io/webmaker-curriculum/WebLiteracyBasics-I/session01-credibility.html)

For easy reference they are:

* Locate relevant information by using search engines
* Compare and contrast information found using multiple searches
* Decide on the trustworthiness of information by identifying key indicators
@smithisgeneric - Do feel free to feedback to @dajbelshaw if you have thoughts on those objectives!

**Comment by smithisgeneric** [comment]
Here are some questions that may be helpful:

1) In the Introduction round, did your learners discuss key indicators for credible information? Check which indicators were identified and discussed:
* Name of author
* Date
* Use of references
* Domain structure (i.e. edu, or gov) 
* Writing quality
* Visuals/design 
* Other (please specify) 
* Unsure
* Not applicable / did not attempt 

2) In the introduction round, which key indicator for credibility raised the most interesting discussion and why?
[Open ended response] 

3) For the Kraken activity, what resources did your learners find? Please select all that apply. 
* Wikipedia 
* Product advertisement
* Images
* News story
* Other (please specify)
* Unsure 
* Not applicable / did not attempt 

4) Did your learners use multiple search strategies?  
* Y
* N
* Unsure 
* Not applicable / did not attempt 

5) If your learners used multiple search strategies, which of the following were attempted?
* Using varied search terms
* Using varied search operators (i.e. AND, OR)
* Searching different types of media on the web (i.e. the web, images, videos, maps) 
* Using multiple search engines
* Visiting a trusted source to search
* Other (please specify) 
* Unsure
* Not applicable / did not attempt 

6) Did your learners utilize analysis and the legit-o-meter tips to analyze whether Kraken exists? 
* Y
* N 
* Unsure
* Not applicable / did not attempt 

7) By the end of your activity, did the majority of your group believe that Kraken is
* Real 
* Imaginary
* Something in between        
* Unsure
* Not applicable / did not attempt 

8) What were the top 3 issues that factored into the debate with your group (choose up to 3):
* Descriptions of Kraken online 
* Images, photographs, or videos of Kraken
* Stories about Kraken 
* Scientific evidence (i.e., fossils) of Kraken or its prey 
* Comparisons to current sea life
* Other (please specify) 
* Unsure 
* Not applicable / did not attempt 

9) Were the introduction round and Kraken activities effective ways to engage learners to examine the credibility of information?
* Highly agree
* Agree
* Neutral
* Disagree
* Highly disagree 
* Unsure 
* Not applicable / did not attempt
 
10) Do you have any comments about the usefulness of the credibility activities in the Introduction round or Kraken activity?

**Comment by LauraHilliger** [comment]
reopening so that we know we need to produce something people can fill in. @smithisgeneric might you put this in the form of a google form?

**Comment by dajbelshaw** [comment]
If we're not localising this in the first instance (i.e. if it's all going to be English for testing) perhaps we could have a friendly 30-second introductory video. That approach seemed to work well for the Web Literacy Map consultation.

**Comment by smithisgeneric** [comment]
Hello, because of my non-staff role with Mozilla, I need to draw a boundary line.  I am not able to be engaged in creating e-forms, sending out to participants, or analyzing responses.  I will follow up with @dajbelshaw @LauraHilliger and Lainie to clarify.

**Comment by dajbelshaw** [comment]
Not a problem. Have assigned myself to this - thanks for doing the hard part @smithisgeneric!

**Comment by dajbelshaw** [comment]
Here we go... http://goo.gl/forms/gnrTJ3d2AW

**Comment by LauraHilliger** [comment]
Nice! Thanks @dajbelshaw and @smithisgeneric! Closing this issue, and filing new ones for comms stuff.

**Comment by ldecoursy** [comment]
Think for testing purposes we want to have this broken into pre-post, and something that the facilitators and learners can take so we really test the learning objectives and ensure they're solid.

**Comment by dajbelshaw** [comment]
We should review the learning objectives ahead of time with staff and mentors. It's the *activities* we need to field test. 

Definitely up for pre-post testing, but are we envisaging putting learners in front of a Google Form from the get-go? Can’t mentors ascertain levels of understanding by methods we suggest?

**Comment by ldecoursy** [comment]
From the 1:1 convos, I personally have been hearing a lot of people want resources they can print, so I'd think the pre-post should be printable too. Agree we want to test the activities, but in part it's testing them against the learning objectives.

**Comment by dajbelshaw** [comment]
Thanks @ldecoursy. Happy to create pre-post questionnaires, but will need guidance as to platform if they need printing too. How will we get the data from the pencil-and-paper forms?

Controlling variables, we need to be *either* testing learning objectives *or* test activities. We'll get woolly feedback otherwise. Let's get the learning objectives reviewed by staff and/or community first - @smithisgeneric & @LauraHilliger have R+

**Comment by LauraHilliger** [comment]
In my mind it's "Does this activity teach these learning objectives", since judging prior knowledge will be hard for anyone who doesn't know their learners well, maybe the pre questionnaire is just a few questions mentors *think* about before their session. Some guidance about on-the-fly assessment of learners. Then we could formulate a question or 2 on the post questionnaire that asks if they thought the session taught x, y, z and the state change they saw?

Just trying to ascertain the goals of the pre questionnaire.

**Comment by LauraHilliger** [comment]
Oh, and on the printing piece - to @dajbelshaw's point, how would we collect that data? Wouldn't it be easier, for the questionnaire at least, to fill in a form?

Curriculum as printable = yay. Filing an issue on that.

**Comment by dajbelshaw** [comment]
Need input from @ldecoursy r.e. scope of pre questionnaire before proceeding.

**Comment by ldecoursy** [comment]
For testing purposes in particular, we should do short (3-ish question) pre/post surveys that map directly to the learning objectives that we can ask mentors/facilitators and learners to fill out. These questions should help us assess the quality of the activity/experience and whether they're helping people meet the learning objectives we've outlined.

For example, for Kraken the  Code:
* How do you know if information you find on a website is valid/trustworthy?

By asking this before and after, we then might be able to say X% of learners are better able to understand/describe if websites are credible. 

Also like asking something along the lines of Karen's #9 and #10 q's above. @smithisgeneric are you able to help put these q's together this week? Starting with this activity: http://mozilla.github.io/webmaker-curriculum/WebLiteracyBasics-I/session01-credibility.html

For the other q's outlined above, I think those would be especially helpful as guiding q's for asking testers to reflect on their experience. We'll have a Discourse thread for testers and our ask will be that they 1) run the activity 2) complete the pre/post questionnaires and 3) do a brief reflection and share feedback.

**Comment by dajbelshaw** [comment]
Awesome. Thanks @ldecoursy! Once @smithisgeneric has created the pre/post questions (which I'm more than happy to help with) I'll transfer them to a Google Form :)

**Comment by smithisgeneric** [comment]
There are still multiple visions expressed here for what the survey questions should be getting at.    

Lainie, I'd caution that an open ended question like "How do you know if information you find on a website is valid/trustworthy?" may not elicit someone's full understanding of credibility and it therefore becomes problematic to do the before and after comparison you're striving for.   

Here is my next round for a shorter list of pre and post questions to try to better understand credibility and search in relation to the activities:

PRE
* How do you think learners seek and find credible information online? (examines search strategies) (open ended)
* How do learners know if information they find on a website is credible? (examines facilitators starting assumptions of credibility assessment) (open ended)
* What are the top three strategies you think will be used by your learners to see if information on a website is credible? (examines strategies) (open ended)


POST

* What strategies did learners identify or use to assess credibility of information in the information round or Kraken activity? Select all that apply.

    Name of author
    Date
    Use of references
    Domain structure (i.e. edu, or gov)
    Writing quality
    Visuals/design
    Other (please specify)
    Unsure
    Not applicable / did not attempt

* How were various information sources weighed during the group work and discussion about whether Kraken is real, imaginary or somewhere in-between? (open ended)   

*  Were the introduction round and Kraken activities effective ways to engage learners to examine the credibility of information?

    Highly agree
    Agree
    Neutral
    Disagree
    Highly disagree
    Unsure
    Not applicable / did not attempt

**Comment by ldecoursy** [comment]
Thank you @smithisgeneric! Chris also mentioned having the learners do pre/post surveys too - do you think we could just adapt the language in this case, or do you think we'd need different questions to get to whether or not they think they've learned what we think they should be learning. ;)

**Comment by jgmac1106** [comment]
Agree with @dajbelshaw re you testing learning objectives and gains or testing material. I caution you on trying to develop measures of gsins this esrly on. I have spent better part of a decade measuring (failing really) this stuff. It is hard. 

For example the open ended question. How would that be coded? Number of idea units? 

Since you are curriculum testing stay away from learning gains and focus on activities.

 Do smaller cognitive labs (verbal protocols)  or a content analysis of the products. 

If you want a quantifuable measure (does this sit well with particapatory assessment) I would check out the ORCA assessment. The new Literacies lab opened it up for use I think..... 

Though I do not think  learning gains is yiur goal. You arr curriculum testing: focus grouos for content validation prior, cognitive labs during, focus groups  after. 

There is no sound reason to give a pretest and plus a pretest before an event activates prior knowledge (good for learning bad for measurent).

**Comment by dajbelshaw** [comment]
Have you got a link to the ORCA assessment, @jgmac1106? We haven't got time to do anything with statistical significance, but we should do the best job we can. 

We're looking for a quick and easy indication that learners are learning *something* useful related to the learning objectives during the sessions. The constraint we've got is that purely mentor-based 'assessment' pre-supposes an existing relationship with learners - and knowledge of what they can do already. That won't necessarily be the case with Clubs where mentors could be meeting learners for the first time.

**Comment by jgmac1106** [comment]
I can email and find out about the ORCA. I attach links to my instruments..



https://www.surveymonkey.com/s/awoodbury
https://www.surveymonkey.com/s/bwoodbury
https://www.surveymonkey.com/s/cwoodbury
https://www.surveymonkey.com/s/dwoodbury

These probably work best in US though as they are about war of independence. 

This last one is just critical evaluation instrument I made. 

https://www.surveymonkey.com/s/GearUpNH

My point though is at this  point in curriculum development you don't look for learning gains,  but if you had to (and this would work offline or online):

- list the indicators you use to know search results are useful
- list the indicators you use to know websites are truthful


You could use relevant and credible but we find the former translate better. 

You then just count the number of indicators pre and post. You could present descriptives (orvt test depending on n) 

Another idea I had was popin. I was playing around last night and you could make wireframe and hotspot questions (where to click to learn more about author, what search term is most relevant). Then your paper and non paper options would be same. 

(sorry for the typos need to stop working when I go to bed...though maybe thats how one defins radical participation)

**Comment by smithisgeneric** [comment]
There were many good points raised by @dajbelshaw @jgmac1106 @LauraHilliger @ldecoursy etc.. 

It looks like @ldecoursy wants a 3 question pre and post survey (6 questions total).  I am still reasonably satisfied with the suggestions I made (in the spirit of keeping it simple) but if you want to add a 4th post question, you may want to take up @dajbelshaw's idea to probe that "learners are learning something useful."  A question could be:
* What was the biggest "aha" moment for your learners during the activity?       
The effectiveness question with the scale and the aha moment question would translate well to use in future evaluations. 

On the questions of surveys for learners, I do not think it would be engaging to try to run a 3 question or rapid survey with learners before the credibility activity. The "introduction round" is already a prior learning assessment and further demonstration of what they already know is put into practice by doing the activity.  The post questions I suggested could be reworded for learners.    

@ldecoursy please let me know if there are additional items you feel need response from me.

**Comment by ldecoursy** [comment]
Thanks so much for all this expert insight @smithisgeneric @dajbelshaw @jgmac1106 @LauraHilliger!  Agree I think for now we're in a good place with @smithisgeneric's latest suggestions - maybe even weave that 4th question as a prompt for the deeper reflection in discourse... Let's try it and see how it goes :) I'll pop into a google form and get into the testing landing page that @thornet has been working on.

**Comment by thornet** [comment]
This is completed in #88, closing.
