### ISSUE TITLE
Create activity / lesson for Reading the Web: Web Mechanics (Ping Kong activity)

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/webmaker-curriculum#80]
What is a fun activity we can do to teach people the basics of search in a production-centered way? Is there a way we can remix the [SEO Battle](https://mousemeredith.makes.org/thimble/seo-battle) to be less about SEO, more about Search and tool agnostic? Or to use the XRay goggles instead of thimble (not sure if that would even work, filing an issue for testing)

I'll file a separate issue for objectives :)

**Comment by dajbelshaw** [comment]
I've had a go at an overview for this. One way would be to use Storify as it has built-in search for lots of different sources (search engines, social networks, etc.) and provides a way for learners to annotate these. 

Anyway, had a go here: https://teach.etherpad.mozilla.org/club-curriculum-remix

Downside would be creation of Storify account. They can login with Facebook/Twitter or could be pre-created accounts (as we've done with Webmaker)?

**Comment by LauraHilliger** [comment]
Would love to hear @keyboardkat and @omnignorant's thoughts on this new search activity. We filed #81 and kept moving on a new activity, probably the smart way to go (since SEO is arguably irrelevant nowadays.) Either of you have thoughts/ideas on using Storify? Alternative tool agnostic search (while making) activities?

**Comment by keyboardkat** [comment]
Cool, moving to #81 now.

**Comment by dajbelshaw** [comment]
Copy/pasting from etherpad...

-----
## Session 1b: Reading the Web: Search (45 mins)**

### Competencies
* Search
* Credibility

### Skills
* Finding real-time or time-sensitive information using a range of search techniques
* Using keywords, search operators, and keyboard shortcuts to make web searches more efficient
* Making judgments based on technical and design characteristics to assess the credibility of information

### Learning objectives
* Find relevant, up-to-date information using a range of search techniques and platforms 
* Use keywords, search operators, and keyboard shortcuts to make web searches more efficient
* Decide on the trustworthiness of information by identifying key indicators

### Tools/resources
* Browser 
*  Planning sheet **(to create)**

### Activities
* Preparation
* Introduction (10 mins)
   * Start off by asking questions of learners like:
   * Where do you get your news?
   * How do you check whether your news sources are trustworthy?
   * When you search the web for information, how do you choose results?
   * Have you ever seen a misleading status update about a news event?
   * What are some recent (news) events that you'd like to find out more about?
* Main activity (30 mins)
   * Learners split into groups of two
   * Use planning sheet to decide what to research 
   * Create a free [Storify](http://storify.com) account **(alternative would be to have accounts pre-made as we've done with Webmaker - depends on audience)**
   * Transfer topic from planning sheet to title of new story in Storify account  
   * Search various sources within Storify to drag-and-drop content
   * Annotate stories / images / status updates with reason for choice
   *Hit publish (optional)
* Reflect/review (5 mins)
   * Some pairs volunteer to share and talk through their story
   * Others critique, ask questions, etc.

**Comment by keyboardkat** [comment]
(moving back from #81 to comment on this specific activity suggestion...) 

I like what you've got going on here, @dajbelshaw. I'm also wondering whether it might be useful to see if any of our lead web literacy club facilitators already doing some of this work with their learners might have curriculum *already* made for Search. 

Will get them involved now, in case!

**Comment by dajbelshaw** [comment]
Thanks @keyboardkat! Looking forward to testing this out (I'm hopefully setting up a Webmaker Club with a friend soon) but would love other ideas!

**Comment by iamjessklein** [comment]
It might not be ready yet - but @toolness and Matthew are [working on a Firefox -> Webmaker add-on](https://redpen.io/p/kr680289eecc1ef9b4) that allows users to identify assets and lightly remix them. I imagine that you can insert the that tool into the activity you are already creating.

**Comment by jgmac1106** [comment]
I am attaching a storify tutorial I made: http://jgregorymcverry.com/storify-as-a-space-for-presence-assessment/ (overview of storify...note it is not that open of a tool) and a tutorial on how to use storify:  http://jgregorymcverry.com/learning-event-nine-in-walkmyworld/

I think one way to make search production centered is to have webmakers design tutorials on how to search. Here is a brief example (scroll down a bit): http://jgregorymcverry.com/plotagon-a-powerful-tool/

@iamjessklein is right. I have access to a ton of great lessons we have developed in our years of researching internet reciprocal teaching. I will put out a call on the LRA listserv as well.

Some activities:
* Another successful thing I find is to have screencasts of different search. Have webmakers annotate what they see happening.
* Playing a simple scavenger hunt
* Find two different answers to the same question. Prove which is correct.
* Thick vs Thin questions

**Comment by thornet** [comment]
Do we have either: 

i) an alternative activity that is offline
ii) a different ending to SEO battle that would work (ideally without creating an account anywhere)? 

@keyboardkat @LauraHilliger @dajbelshaw @omnignorant 

A lot of feedback from the interviews is that offline is needed; it'd be great to offer that in this section. 

Here's an offline alternative from Mouse that seems good. However, Meredith says the facilitator needs good prep, so it may be too hard for now. 

https://mousemeredith.makes.org/thimble/LTE0NDMxNjgyNTY=/ping-kong-activity

**Comment by jgmac1106** [comment]
Here are two offline search tasks I have done in the past (and one I have never tried):

- Given a broad research question can you widdle this down into topics and then change those topics into search terms?
-Annotate a search result page. Actually very important. There are reoccuring text structures than be reinforced.


-Build a results page. Create two sets of cards. One with the search terms and one with separate search results. Given a search term build a list of what you think would be the most relevant results.

-Search Engine Bingo. Have a bingo card with search  terms. Read out what was a number one result. Do not tell players the search term used. If they think they have it they cover up the bingo chip.

(I said three but thought of bingo as I was typing).

**Comment by keyboardkat** [comment]
Thanks for your additions @jgmac1106 -- these are great ideas, and I love the creative approaches you take to Storify! On Twitter you mention you made a Storify to explain what you did with Storify (ha) -- do you have a link for that? 

@ all: Looks like we'll hold back on asking other Webmaker community members to dive into this bug for now, since we're still building the codesign strategy for this kind of contribution -- this will allow us to move ahead with this issue in the meantime. 

@thornet @LauraHilliger @dajbelshaw good point re: adding an offline option to this pathway. big plus. Given the potential difficulty of King Kong (altho I don't think it's that bad, actually) we could instead customize the excellent [Web Mechanics Speed Dating](https://juliahivenyc.makes.org/thimble/MTgwOTQ0ODk2/web-mechanics-speed-dating) offline activity by Julia Vallera, which was made specifically for [offline environments](https://keyboardkat.makes.org/thimble/LTIxMDA3NTY0ODA=/lofi-nofi-teaching-kit). 

What do folks think?

**Comment by jgmac1106** [comment]
@keyboardkat I threw both of my examples up of my stuff on storify. I can easily make one based on @dajbelshaw Storify lesson plan.

Only thing I might add to the storify lesson is to write a source analysis under each event added. Why is this piece relevant? Who shared the link, why do you trust this person to curate? Who is the source of the link? What makes the author or publisher credible?

@keyboardkat Trying to get figure out the discourse of git. I always envisioned issue reports to be like bug reports and not so much open discussions. Trying to figure out the difference for git and discourse and what conversations go where.

**Comment by jgmac1106** [comment]
But this sounds more like credibility. Re-read the Storify lesson plan. It already gets at relevancy. My suggestions were source judgments and wouldn't belong in a search lesson..

**Comment by dajbelshaw** [comment]
Happy to re-scope the activity to be offline (might be nice for some of the sessions to be entirely paper-based!) but I guess we need to make a decision as to whether we going to:

A) Create *two* activities (one online, one offline) that both meet the learning objectives
B) Create *one* activity that works offline

Thoughts? If it's the former, we'll need to separate out this thread into a couple of issues. :)

**Comment by thornet** [comment]
Based on the above suggestions, what if you fork depending on your connectivity: 

1. (on/offline) Annotate Search Results.
   - If offline, mentor can bring print-outs of prior searches. 
   - Include @jgmac1106's source analysis as part of the annotation, so we build on Credibility.  

2a (online). Zero Search Results Hunt.
   - Take first part of SEO Battle

2b (offline). Ping Kong.
   - Use the searches from activity 1 as examples for your route. 
   - Can add online components if you have time and connectivity. 
   - Gets us covering Web Mechanics in addition to Search.

**Comment by thornet** [comment]
Or, for simplicity, we just try Ping Kong. 

Part of testing is calibrating the difficulty level, and Ping Kong is ready to go. (We need this by end of week).

**Comment by thornet** [comment]
In progress porting Ping Kong: http://mozilla.github.io/webmaker-curriculum/WebLiteracyBasics-I/session01-search.html

**Comment by thornet** [comment]
Now at: http://mozilla.github.io/webmaker-curriculum/WebLiteracyBasics-I/session01-pingkong.html

@omnignorant @dajbelshaw @ldecoursy could you proofread?

- [] add learning objectives
- [] image attribution
- [] proofread
- [] check links

**Comment by thornet** [comment]
Closing this ticket and made one for proofreading: https://github.com/mozilla/webmaker-curriculum/issues/126
