### ISSUE TITLE
Test whether you can SEO Battle w/ the XRay goggles

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/webmaker-curriculum#81]
if you make a page with the XRay goggles and put in a unique crazy word, then publish, will google return a result? EG do googlebots search our DBs?

**Comment by dajbelshaw** [comment]
I think that's a question for @toolness

**Comment by toolness** [comment]
Actually, I don't know the answer to that, because I don't control the server-side stuff that happens with the goggles right now. @jbuck, do you have any idea whether google indexes X-Ray Goggles makes, or know someone who might have an answer?

**Comment by jbuck** [comment]
@toolness I *think* it does because one of the Thimble makes did a similar thing. Only way to know for sure is to try it though!

**Comment by LauraHilliger** [comment]
ok, made a random page: http://laura.makes.org/goggles/lauras-remix-of-google-2 will need to wait a bit to see if you can search for "batify the baboonal" and return results....

**Comment by keyboardkat** [comment]
haha, i would love to see this work...

**Comment by dajbelshaw** [comment]
Hey @keyboardkat it is indeed the page you link to. As you can see, there's a 'Learn to Remix Content' button that takes you through to a (GitHub) [wiki page](https://github.com/mozilla/webmaker-curriculum/wiki/How-to-remix-Learning-Activities). Do feel free to help with that!

**Comment by LauraHilliger** [comment]
CLosing this ticket. XRay goggles won't work for seo battle. We should use the activity @dajbelshaw put together in #80.

@keyboardkat not sure if you clicked through, but I transferred the kraken activity to github here: http://mozilla.github.io/webmaker-curriculum/WebLiteracyBasics-I/credibility-kraken.html
code: https://github.com/mozilla/webmaker-curriculum/blob/master/WebLiteracyBasics-I/credibility-kraken.html

Please file a new ticket for edits/changes/remixes etc to that activity. YOU :straight_ruler:
