### ISSUE TITLE
Write learning objectives for Kraken activity

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/webmaker-curriculum#82]
related to #80

**Comment by dajbelshaw** [comment]
First stab: https://teach.etherpad.mozilla.org/club-curriculum-remix

**Comment by LauraHilliger** [comment]
R+ from me filed #88 and pinged @smithisgeneric for QA. Karen - feel free to just close this issue if you're ok with the objectives.

**Comment by dajbelshaw** [comment]
Renamed this for clarity and closed.
