### ISSUE TITLE
Collect Github Repos that have #teachtheweb curricular content

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/webmaker-curriculum#85]
Github (and our [Mozilla wiki](http://wiki.mozilla.org)) attracts open sourcers, so if we collect links to repos that have relevant #teachtheweb content, we can fork, parse and pull, remix and explore what "github for curriculum" means for everyone :) 

***In a box model***
https://github.com/p2pu/course-in-a-box
https://github.com/jmswisher/DevTopicInABox
https://wiki.mozilla.org/ReMo/SOPs/AppDaysInABox
https://wiki.mozilla.org/ReMo/SOPs/StumblingInABox

***Lessons***
https://github.com/chrisdavidmills/basic-practical-web-design-skills
https://github.com/chrisdavidmills/beginning-web
https://github.com/ScriptEdcurriculum/curriculum
https://github.com/carlsednaoui/coderdojo-nyc-curriculum
https://github.com/matteomenapace/codeclub

**Comment by keyboardkat** [comment]
Not on Github (they've chosen to use Google Drive instead for this purpose) but Ladies Learning Code has shared this great set of curriculum packs with us, too: http://ladieslearningcode.com/making-makers/

**Comment by LauraHilliger** [comment]
ref'd in Mozilla-Learning (closing here)
