### ISSUE TITLE
Make questionnaire for Reading the Web: Credibility (Kraken activity) 

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/webmaker-curriculum#88]
The learning objectives are in #82 (and here again for easy reference). @smithisgeneric - @dajbelshaw and I were chatting and want to reiterate that if you think we should shift the objectives so your evaluations are easier to formulate / test, just comment in #82!

Search Learning objectives
* Find relevant, up-to-date information using a range of search techniques and platforms 
* Using keywords, search operators, and keyboard shortcuts to make web searches more efficient
* Decide on the trustworthiness of information by identifying key indicators

**Comment by smithisgeneric** [comment]
These objective look fine to me.  I am noticing some overlap (i.e. between credibility and search) but think that this is fine because competencies and skills oftern overlap in production-centered activities.

**Comment by dajbelshaw** [comment]
I think we need to re-open this to get the questions written. Wondering if @smithisgeneric is happy *writing* the questions (and then I can move to Google Forms) or...?

**Comment by smithisgeneric** [comment]
Happy to advise on appropriate questions.  It is easiest to view the learning activities.  Are [the activities in issue 80] (https://github.com/mozilla/webmaker-curriculum/issues/80) the firm version?

**Comment by dajbelshaw** [comment]
I *think* so. AFAIK @LauraHilliger is happy with it. Just waiting for @keyboardkat and @omnignorant to review, I guess.

**Comment by keyboardkat** [comment]
I'm going to ask a few community members to weigh in re: the curriculum itself on Issue #80, but as I get the sense these Learning Objectives are not entirely dependent on said curriculum's content, I'd say go for it?

**Comment by LauraHilliger** [comment]
@smithisgeneric due to #81 I think these activities/VERY similar activities are firm. @keyboardkat or someone reading this might come up with a slightly different search activity but I agree with Kat - the learning objectives can be fixed in this case.

**Comment by thornet** [comment]
Cross-posting completed questionnaires for easy reference (thanks, all!) and closing this ticket. 

Link to pre survey: http://goo.gl/forms/Uua6yKIy5E
Link to post survey: http://goo.gl/forms/ezm6IXWhhM
