### ISSUE TITLE
Create a glossary of terms for Webmaker Clubs

### ISSUE THREAD

**Issue by dajbelshaw** [mozilla/webmaker-curriculum#89]
Per Issue #8 let's create a glossary for terms as we build assets and resources. Everything from super-simple (e.g. what we mean by 'remix') up to more pedagogical terms (if they're necessary to include).

**Comment by dajbelshaw** [comment]
Writing this here: https://github.com/mozilla/webmaker-curriculum/wiki/Glossary

**Comment by dajbelshaw** [comment]
Please do dump some terms in and I'll have a go at writing some definitions :)

https://github.com/mozilla/webmaker-curriculum/wiki/Glossary

**Comment by thornet** [comment]
Bumping this up a priority per @dajbelshaw's suggestion so we can include terms needed in Ping Kong activity.

**Comment by dajbelshaw** [comment]
OK, working on this. Worth noting that we can link to each term from the activities - e.g. [Ping](https://github.com/mozilla/webmaker-curriculum/wiki/Glossary#ping)

**Comment by thornet** [comment]
Cool. I'm adding the link to the full wiki page now. If we want, we can go back later and mark individual ones.

**Comment by dajbelshaw** [comment]
Done!
