### ISSUE TITLE
Toggle Navigation (mobile) doesn't work

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/webmaker-curriculum#92]
I tried to figure it out for a while and eventually said, "Meh, I'm asking @secretrobotron for help". 

I've built in a nav bar onto all the curriculum pages [for example](http://mozilla.github.io/webmaker-curriculum/WebLiteracyBasics-I/). The nav should disappear and become toggleable when you size the browser window. It disappears, but...well it just disappears.

**Comment by secretrobotron** [comment]
I'd look into the classes and media-queries of some of the elements you're using. For example `.navbar-nav` is wrapped in `@media (min-width: 768px)`, so some of its properties are only applied when the window is > 768px in width.

This might be a consequence of using maker strap, and @k88hudson might be smarter than me there.

**Comment by k88hudson** [comment]
I *do* see the toggle button when the window is smaller, but you need to use some javascript to hide/show your menu when that button is clicked.

You can do this using http://getbootstrap.com/javascript/#collapse

**Comment by k88hudson** [comment]
Alternatively, you can just add/remove the `collapse` class

**Comment by LauraHilliger** [comment]
hmm...i think you cats are overestimating my skillz (or rather the time I have to go about improving them)...is the plugin included in makerstrap? This is where I'm at, but it doesn't work:

'''
<div>
                
                	<button type="button" class="navbar-toggle" ng-click="collapseToggle()" data-toggle="collapse" aria-expanded="false" aria-controls="collapseNav" data-target="collapseNav">
						<span class="sr-only">Toggle navigation</span>
						<span class="fa fa-bars fa-lg"></span>
					</button>
				
                 <a href="#" class="logo webmaker-logo"><img src="https://webmaker.org/img/logo.png"></a>

                <ul class="nav navbar-nav navbar-right navbar-collapse text-center-xs collapse" id="collapseNav">
                    <li>
                        <a href="https://twitter.com/hashtag/teachtheweb">#TeachTheWeb</a>
                    </li>

                    <li>
                        <a href="http://discourse.webmaker.org/category/clubs">Discussion</a>
                    </li>

                    <li>
                        <a href="https://github.com/mozilla/webmaker-curriculum/blob/master/WebLiteracyBasics-I/session01-credibility.html">View on Github</a>
                    </li>
                </ul>
            </div>
'''

**Comment by dajbelshaw** [comment]
Can anyone help with this while @LauraHilliger is away? Perhaps @k88hudson if she's got some time to dive into the repo?

**Comment by LauraHilliger** [comment]
will be covered in https://github.com/MozillaFoundation/Mozilla-Learning/issues/47
