### ISSUE TITLE
Decide on copy for discourse link

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/webmaker-curriculum#96]
We should get into the habit of sending people to discourse from our wiki pages. From #73 I added

Have thoughts on this? Join our community forum!

and link to discourse.webmaker.org

This issue is to finalize the copy and the URL - should we send people to the clubs category? Or perhaps the "Training>Exploring" which is about pedagogy? What should this say? 

cc/ @keyboardkat @iamjessklein @dajbelshaw

**Comment by dajbelshaw** [comment]
Rather than directing people to a specific thread, I think we should create a custom footer for the wiki to be shown on *all* pages. This can to inform people of the #TTW forum (generally) and the specific category. 

Sample text below:

> Have thoughts on this? Join our [community forum](http://discourse.webmakerprototypes.org/)! (you may find the discussion threads in the [Clubs section](http://discourse.webmaker.org/category/clubs) of most use.
