### ISSUE TITLE
Roadmap new curricular structure

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/webmaker-curriculum#97]
**Update:** latest iteration is [here](https://github.com/mozilla/webmaker-curriculum/issues/97#issuecomment-73267007)

----

We have:

*Web Literacy Basics I*
* Reading the Web: Credibility
* Reading the Web: Search
* Writing the Web: Composing for the Web
* Participating on the Web: Open Practices

We need to define where we go from there. Potentially, we could use the original meta-arc and remix it to follow this format. Braindump:

*Web Literacy Basics II*
* Reading the Web: Navigation (covering URL structure, browser features, common iconography)
* Reading the Web: Search (advanced search techniques)
* Reading the Web: Web Mechanics (advanced search techniques)
* Writing the Web: Remixing (HTML + CSS) (this will have to be a double, triple or quadruple session, i think.)
* Participating on the Web: Privacy (x 2 sessions, concept vs practice)

*Web Literacy Basics III*
* Reading the Web: Security
* Writing the Web: Design and Accessibility
* Participating on the Web: Sharing

**Comment by dajbelshaw** [comment]
I guess it depends what our theory is around progression. To what extent is Web Literacy Basics I-III a progression - as opposed to a smörgåsbord - of activities?

Suggest we make enhancements / build out the wiki until @thornet returns from PTO.

**Comment by dajbelshaw** [comment]
OK, so here's my $0.02, riffing off @LauraHilliger's braindump above. This is dependent on a couple of (potential) changes coming in Web Literacy Map v1.5:
* **Infrastructure** merging with **Web Mechanics** (see [this issue](https://github.com/mozilla/webliteracymap/issues/10))
* **Design/Accessibility** separating out into two distinct competencies (see [this issue](https://github.com/mozilla/webliteracymap/issues/13))

With these tweaks, I think we can cover all 15 competencies with five per module.

# Web Literacy Basics I
* Credibility
* Web Mechanics
* Composing for the Web
* Remixing
* Open Practices

# Web Literacy Basics II
* Navigation
* Search
* Design
* Collaborating
* Privacy

# Web Literacy Basics III
* Security
* Accessibility
* Coding/scripting
* Sharing
* Community Participation

-----
I think this would give us a nice mix of competencies that are somewhat related to one another. We can also choose scaffold this or leave each as being on the same 'level'.

Would love to know your thoughts @thornet @LauraHilliger @ldecoursy et al. :)

**Comment by ldecoursy** [comment]
Seems like a good flow to me (knowing that many activities will cross over competencies and hopefully draw on/reinforce skills learned earlier in the process). Would be good to get the curriculum working group's weigh-in once we have that group identified after tomorrow's call.

**Comment by dajbelshaw** [comment]
Just flagging that in Issue #113 I've [flagged a potential need](https://github.com/mozilla/webmaker-curriculum/issues/113#issuecomment-71480839) to switch **Designing for the Web** and **Remixing**.

**Comment by dajbelshaw** [comment]
OK, taking another stab knowing that we'll need _two_ activities for the **Participating on the Web** part of **Web Literacy Basics I**. Let's just focus on the first couple of modules to begin with:

# Web Literacy Basics I

## Reading
- Credibility 
- Web Mechanics

## Writing
- Composing for the Web
- Remixing

## Participating
- Open Practices
- Privacy

# Web Literacy Basics II

## Reading
- Navigation
- Search

## Writing
- Designing for the Web
- Coding/scripting

## Participating
- Collaborating
- Privacy

---

Would love feedback from @thornet & @ldecoursy!

**Comment by dajbelshaw** [comment]
This issue was moved to MozillaFoundation/Mozilla-Learning#91
