### ISSUE TITLE
COMMS: Invite Club cohorts to fill in Credibility questionnaire. 

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/webmaker-curriculum#98]
The thought was to have Club testers

1. [Run the session](http://mozilla.github.io/webmaker-curriculum/WebLiteracyBasics-I/session01-credibility.html)
2. [Fill in the questionnaire](http://goo.gl/forms/gnrTJ3d2AW)

We'll need comms to invite folks to do so. I'm thinking just a simple bit of email text that we can send to the folks who agreed to help with testing.

**Comment by thornet** [comment]
Yep! Drafted here: 

https://teach.etherpad.mozilla.org/testing
